# site settings
title: Crypto Tips and Musts
subtitle: by Harry Eldridge and Brendan Doyle
email: bjd54@georgetown.edu
description: An android developer's guide to not making common cryptographic mistakes.
baseurl: "/cryptoTips" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: Georgetown University
city: Washington D.C.
state: DC
zip_code: 20007
country: United States of America
phone: (410) 829-9908

# social settings
500px_url:
facebook_url:
github_url: https://github.com/bdoyle0182
gitlab_url: 
googleplus_url:
instagram_url:
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
